source 'https://rubygems.org'


gem 'rails', '>= 5.0.0.beta3', '< 5.1'
gem 'sqlite3'
gem 'puma'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem "devise", :github => 'plataformatec/devise', :branch => 'master'
gem "omniauth"
gem 'haml', '~> 4.0.7'
gem 'kaminari', '~> 0.16.3'  
gem 'jquery-rails'
gem 'turbolinks', '~> 5.x'
gem 'jbuilder', '~> 2.0'
gem 'bootstrap-sass', '~> 3.3.6'  
gem 'simple_form'
gem 'will_paginate',  :github => 'mislav/will_paginate'
gem 'bootstrap-will_paginate', '0.0.10'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
